=== alpheios-project/schemas/xsd/aligned-text-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2014 
  
  The Alpheios Project
  http://alpheios.net
  
  Tufts University
  
  Ycan redistribute it and/or modify it under the terms of the GNU General 
  Public License as published by the Free Software Foundation, either version 3 
  of the License, or (at your option) any later version.
  
  This file is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License <http://www.gnu.org/licenses/> for more details.
-->

<!--
  Schema describing text alignment
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  attributeFormDefault="unqualified" xmlns:align="http://alpheios.net/namespaces/aligned-text/2.0"
  xmlns:prov="http://www.w3.org/ns/prov#" xmlns:alphdt1="http://alpheios.net/namespaces/datatypes/1"
  targetNamespace="http://alpheios.net/namespaces/aligned-text/2.0" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">

  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:import namespace="http://alpheios.net/namespaces/datatypes/1" schemaLocation="datatypes-1.0.xsd"/>  

  <xs:annotation>
    <xs:documentation>Structure of aligned translation data</xs:documentation>
  </xs:annotation>

  <!-- Top-level element -->
  <xs:element name="aligned-text">
    <xs:annotation>
      <xs:documentation>
        Alignment data for a set of beads of text
          @document_uri uri identifier for this document
          @version optional version of the alignment schema used
          comment = optional comments
          link = optional links to related documents
          citeprefix = optional list of prefix definitions for cite references used in the document
          bead = alignment beads in the text
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:choice maxOccurs="unbounded">
        <xs:element name="comment" type="xs:anyType" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="link" type="alphdt1:LinkType" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation></xs:annotation>
        </xs:element>
          <xs:element name="bead" type="align:BeadType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:choice>
      <xs:attribute name="document_uri" type="xs:anyURI" use="required">
        <xs:annotation>
          <xs:documentation>Specifies a unique uri for this alignment document</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="version" type="xs:string" use="optional">
        <xs:annotation>
          <xs:documentation>Specifies the version of the alignment schema used for this document</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="citeprefix" type="alphdt1:CitePrefixType">
        <xs:annotation>
          <xs:documentation>
            An optional list of prefix definitions for cite references in this document
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
  <!-- Bead -->
  <xs:complexType name="BeadType">
    <xs:annotation>
      <xs:documentation>
        Alignment data for a single chunk of text
        @n identifier for word set
        @type optional specifier of the semantic classification of the wordset
        @one-to-one optional boolean flag to indicate if one-to-one alignment
        Typically consists of two word sets:
          wds[@n='ws1'] = words from original text
          wds[@n='ws2'] = words from translated text
        Optional comments may be interspersed in the word sets
      </xs:documentation>
    </xs:annotation>
    <xs:choice maxOccurs="unbounded">
      <xs:element name="comment" type="xs:anyType"/>
      <xs:element name="wds" type="align:WordSetType"/>
    </xs:choice>
    <xs:attribute name="n" type="alphdt1:NSeqType" use="required"/>
    <xs:attribute name="one-to-one" type="xs:boolean"/>
    <xs:attribute name="type" type="xs:string">
      <xs:annotation>
        <xs:documentation>
          Semantic classification of this bead (e.g. 'sentence', 'verse', etc.)
          May be a URI representing a term in a controlled vocabulary.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <!-- Set of words from a language -->
  <xs:complexType name="WordSetType">
    <xs:annotation>
      <xs:documentation>
        Set of words from a language
          @n word set identifier (required)
          @xml:lang language code for this set of words (required)
          @dir optional text direction for this set of words (default is ltr)
          @cite optional cite reference for the source of the words
          comment = optional comments
          w = words
      </xs:documentation>
    </xs:annotation>
    <xs:choice maxOccurs="unbounded">
      <xs:element name="comment" type="xs:anyType"/>
      <xs:element name="w" type="align:WordType"/>
    </xs:choice>
    <xs:attribute name="n" type="align:WordSetIdType" use="required"/>
    <xs:attribute ref="xml:lang" use="required"/>
    <xs:attribute name="dir" type="alphdt1:LanguageDirType" use="optional"/>
    <xs:attribute name="cite" type="alphdt1:CiteType" use="optional">
      <xs:annotation>
        <xs:documentation>
          Specifies one or more canonical citation references for the group of words 
          (e.g. the CTS urn for the work, edition and passage and subreference from 
          which it comes).
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <!-- Single word -->
  <xs:complexType name="WordType">
    <xs:annotation>
      <xs:documentation>
        Single word
          @n = word id
          @xml:lang optional language code for this word (overrides attribute on parent)
          @dir optional text direction for this set of words (overrides attribute on parent)
          @cite optional cite reference for the source of the words
          text = the actual word
          comment = optional comments
          refs = list of aligned words
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="text" type="xs:string"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="comment" type="xs:anyType"/>
        <xs:element name="refs" type="align:RefType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="n" use="required" type="align:WordIdType"/>
    <xs:attribute ref="xml:lang" use="optional"/>
    <xs:attribute name="dir" type="alphdt1:LanguageDirType" use="optional"/>
    <xs:attribute name="cite" type="alphdt1:CiteType" use="optional">
      <xs:annotation>
        <xs:documentation>
          Specifies a canonical citation reference for the word  
          (e.g. the CTS urn for the work, edition and passage and subreference 
          from which it comes).
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <!-- List of word references -->
  <xs:complexType name="RefType" mixed="true">
    <xs:annotation>
      <xs:documentation>
        List of word references
          @nrefs = list of word ids
          @wref = identifier of the wds element (word set) to which the 
                  word ids in the nrefs attribute refers
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="nrefs" type="align:WordListType" use="required"/>
    <xs:attribute name="wref" type="align:WordSetIdType" use="required"/>
  </xs:complexType>
  
  <!-- Word identifier attribute -->
  <xs:simpleType name="WordIdType">
    <xs:annotation>
      <xs:documentation>
        Type of word id attribute: &lt;sentenceNumber&gt;-&lt;wordNumber&gt;
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <!--  <xs:pattern value="[1-9][0-9]*[a-z]?-[1-9][0-9]*[a-z]?"/> -->
    </xs:restriction>
  </xs:simpleType>

  <!-- Word list attribute -->
  <xs:simpleType name="WordListType">
    <xs:annotation>
      <xs:documentation>
        Type of word list attribute: space-separated list of word ids
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="[^ ]+( [^ ]+)*"/>
      <!--  <xs:pattern value=
        "[1-9][0-9]*[a-z]?-[1-9][0-9]*[a-z]?( [1-9][0-9]*[a-z]?-[1-9][0-9]*[a-z]?)*"
      /> -->
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Wordset identifier attribute -->
  <xs:simpleType name="WordSetIdType">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

</xs:schema>

=== alpheios-project/schemas/examples/alignment.xml
<?xml version='1.0' encoding='UTF-8'?>
<aligned-text xmlns="http://alpheios.net/namespaces/aligned-text/2.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://alpheios.net/namespaces/aligned-text/2.0 ../xsd/aligned-text-2.0.xsd"
 document_uri="http://data.perseus.org/collections/urn:cite:perseus:align.1.1"
 citeprefix="doc1: urn:cts:greekLit:tlg059.tlg002.perseus-grc1: 
             doc2: urn:cts:greekLit:tlg059.tlg002.perseus-eng1:
             doc3: urn:cts:greekLit:tlg059.tlg002.perseus-fre1:"
 version="2.0">
    <comment class="title">
        Sample Alignment of first few words of Plato's Apology to show 
        use of new schema for 3 language alignment
    </comment>
    <comment class="stdabbrev">Plat. Apol. 17a</comment>
    <link rel="http://www.w3.org/ns/prov#has_provenance" href="provenance-URI"/>
    <link rel="http://www.w3.org/ns/prov#has_anchor" href="target-URI"/>  
    <bead n="1" type="verse">
        <wds n="ws1" cite="doc1:17a" xml:lang="greek" dir="ltr">
            <w n="1-1" cite="doc1:17a@ὅτι[1]" dir="ltr">
                <text>ὅτι</text>
                <refs nrefs="1-1" wref="ws2"/>
                <refs nrefs="1-1" wref="ws3"/>
            </w>
            <w n="1-2" cite="doc1:17a@μὲν[1]">
                <text>μὲν</text>
                <refs nrefs="1-1" wref="ws2"/>
            </w>
            <w n="1-3" cite="doc1:17a@ὑμεῖς[1]">
                <text>ὑμεῖς</text>
                <refs nrefs="1-2" wref="ws2"/>
            </w>
            <w n="1-4" cite="doc2:17a@,[1]">
                <text>,</text>
            </w>
            <w n="1-5" cite="doc1:17a@ὦ[1]">
                <text>ὦ</text>
            </w>
            <w n="1-6" cite="doc1:17a@ὑμεῖς[1]">
                <text>ἄνδρες</text>
                <refs nrefs="1-4 1-5" wref="ws2"/>
            </w>
        </wds>
        <wds n="ws2" cite="doc2:17a" xml:lang="eng" dir="ltr">
            <w n="1-1" cite="doc2:17a@How[1]">
                <text>How</text>
                <refs nrefs="1-1 1-2" wref="ws1"/>
            </w>
            <w n="1-2" cite="doc2:17a@you[1]">
                <text>you</text>
                <refs nrefs="1-3" wref="ws1"/>
            </w>
            <w n="1-3" cite="doc2:17a@,[1]">
                <text>,</text>
            </w>
            <w n="1-4" cite="doc2:17a@men[1]">
                <text>men</text>
                <refs nrefs="1-6" wref="ws1"/>
            </w>
            <w n="1-5" cite="doc2:17a@of[1]">
                <text>of</text>
                <refs nrefs="1-6" wref="ws1"/>
            </w>
        </wds>
        <wds n="ws3" cite="doc3:17a" xml:lang="fre" dir="ltr">
            <w n="1-1" cite="doc3:17a@Comment[1]">
                <text>Comment</text>
                <refs nrefs="1-1 1-2" wref="ws1"/>
                <refs nrefs="1-1" wref="ws2"/>
            </w>
            <w n="1-2" cite="doc3:17a@vous[1]">
                <text>vous</text>
                <refs nrefs="1-3" wref="ws1"/>
                <refs nrefs="1-2" wref="ws2"/>
            </w>
            <w n="1-3" cite="doc3:17a@,[1]">
                <text>,</text>
            </w>
            <w n="1-4" cite="doc3:17a@des[1]">
                <text>des</text>
                <refs nrefs="1-6" wref="ws1"/>
                <refs nrefs="1-4 1-5" wref="ws2"/>
            </w>
            <w n="1-5" cite="doc3:17a@hommes[1]">
                <text>hommes</text>
                <refs nrefs="1-6" wref="ws1"/>
                <refs nrefs="1-4 1-5" wref="ws2"/>
            </w>
            <w n="1-6" cite="doc3:17a@qui[1]">
                <text>qui</text>
                <refs nrefs="1-6" wref="ws1"/>
                <refs nrefs="1-4 1-5" wref="ws2"/>
            </w>
        </wds>
    </bead>
</aligned-text>

=== alpheios-project/schemas/examples/Isidore_Etymology.align.xml
<?xml version='1.0' encoding='UTF-8'?>
<aligned-text xmlns="http://alpheios.net/namespaces/aligned-text/2.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://alpheios.net/namespaces/aligned-text/2.0 ../xsd/aligned-text-2.0.xsd"
 document_uri="http://data.perseus.org/collections/urn:cite:perseus:align.1.1"
 citeprefix="doc1: http://penelope.uchicago.edu/Thayer/L/Roman/Texts/Isidore/1*.html 
             doc2: http://pot-pourri.fltr.ucl.ac.be/files/AClassftp/TEXTES/ISIDORUS/Etymologie/B1N8PWGetQy.pdf
            "
 version="2.0">
    <comment class="title">
        Sample Alignment of a sentence from Isidore's Etymologies to show 
        use of new schema for alignment of multi-lingual text from a source document outside Perseus. 
    </comment>
    <comment class="stdabbrev"></comment>
    <link rel="http://www.w3.org/ns/prov#has_provenance" href="provenance-URI"/>
    <link rel="http://www.w3.org/ns/prov#has_anchor" href="target-URI"/>  
    <bead n="1" type="verse">
        <wds n="ws1" cite="doc1:#21" xml:lang="la" dir="ltr">
            <w n="1-1" cite="doc1:#21" dir="ltr">
                <text>A diple-periestigmene-sign (a V pointing to the right, with a dot on either side of the point) </text>
                <refs nrefs="1-1" wref="ws2"/>
            </w>
            <w n="1-2" cite="doc1:#21@diple[3]">
                <text>Diple</text>
                <refs nrefs="1-2 1-3" wref="ws2"/>
            </w>
            <w n="1-3" cite="doc1:#21@περιεστιγμένη[1]" xml:lang="grc">
                <text>περιεστιγμένη</text>
                <refs nrefs="1-4" wref="ws2"/>
            </w>
            <w n="1-4" cite="doc2:#21@id[3]">
                <text>id</text>
                <refs nrefs="1-6" wref="ws2"/>
            </w>
            <w n="1-5" cite="doc1:#21@est[9]">
                <text>est</text>
                 <refs nrefs="1-7" wref="ws2"/>
            </w>
            <w n="1-6" cite="doc1:#21@cum[5]">
                <text>cum</text>
                <refs nrefs="1-9" wref="ws2"/>
            </w>
            <w n="1-7" cite="doc1:#21@geminis[1]">
                <text>geminis</text>
                <refs nrefs="1-10" wref="ws2"/>
            </w>
            <w n="1-8" cite="doc1:#21@punctis[1]">
                <text>punctis</text>
                <refs nrefs="1-11" wref="ws2"/>
            </w>
        </wds>
        <wds n="ws2" cite="doc2:1.21.15" xml:lang="en" dir="ltr">
            <w n="1-1" cite="doc2:1.21.15">
                <text>A diple-periestigmene-sign (a V pointing to the right, with a dot on either side of the point)</text>
                <refs nrefs="1-1" wref="ws1"/>
            </w>
            <w n="1-2" cite="doc2:1.21.15@the[1]">
                <text>The</text>
                <refs nrefs="1-2" wref="ws1"/>
            </w>
            <w n="1-3" cite="doc2:1.21.15@diple[1]" xml:lang="lat">
                <text>diple</text>
                <refs nrefs="1-2" wref="ws1"/>
            </w>
            <w n="1-4" cite="doc2:1.21.15@περιεστιγμένη[1]" xml:lang="grc">
                <text>περιεστιγμένη</text>
                <refs nrefs="1-3" wref="ws1"/>
            </w>
            <w n="1-5" cite="doc2:1.21.15@,[1]">
                <text>,</text>
            </w>
             <w n="1-6" cite="doc2:1.21.15@that[1]">
                <text>that</text>
                <refs nrefs="1-4" wref="ws1"/>
            </w>
             <w n="1-7" cite="doc2:1.21.15@is[1]">
                <text>is</text>
                <refs nrefs="1-5" wref="ws1"/>
            </w>
            <w n="1-8" cite="doc2:1.21.15@,[2]">
                <text>,</text>
            </w>
            <w n="1-9" cite="doc2:1.21.15@with[1]">
                <text>with</text>
                <refs nrefs="1-6" wref="ws1"/>
            </w>
             <w n="1-10" cite="doc2:1.21.15@two[1]">
                <text>two</text>
                <refs nrefs="1-7" wref="ws1"/>
            </w>
             <w n="1-11" cite="doc2:1.21.15@points[1]">
                <text>points</text>
                <refs nrefs="1-8" wref="ws1"/>
            </w>
        </wds>
        
    </bead>
</aligned-text>
