=== alpheios-project/schemas/xsd/treebank-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2014 
  
  The Alpheios Project
  http://alpheios.net
  
  Perseus Digital Library, Tufts University
  http://www.perseus.tufts.edu
  
  Ycan redistribute it and/or modify it under the terms of the GNU General 
  Public License as published by the Free Software Foundation, either version 3 
  of the License, or (at your option) any later version.
  
  This file is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License <http://www.gnu.org/licenses/> for more details.
-->

<!--
  Treebank schema version 2.0
-->
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xml="http://www.w3.org/XML/1998/namespace"
	xmlns:alphdt1="http://alpheios.net/namespaces/datatypes/1"
	xmlns:treebank="http://data.perseus.org/ns/syntax/treebank/2"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
    vc:minVersion="1.1" 
    targetNamespace="http://data.perseus.org/ns/syntax/treebank/2"
    elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" 
		schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:import namespace="http://alpheios.net/namespaces/datatypes/1" 
		schemaLocation="datatypes-1.0.xsd"/>  
	<xs:import namespace="http://alpheios.net/rdfvocab/inflections/1" 
		schemaLocation="alph-infl-att.xsd"/>  
	
	<xs:include schemaLocation=""></xs:include>
	
	<xs:element name="treebank">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="link" type="alphdt1:LinkType" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>
							Use to specify links to provenance information and format descriptors.
							Where possible use controlled vocabulary to type the link relations:
							For provenance documents:
								http://www.w3.org/ns/prov#has_provenance
								http://www.w3.org/ns/prov#has_anchor
							For format descriptors:
								http://purl.org/dc/terms/format
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="comment" type="xs:anyType" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>
							May be used to add document level comments and metadata.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="sentence" type="treebank:sentenceType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>
						Version of the treebank schema used. 
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="optional">
				<xs:annotation>
					<xs:documentation>
						Language code for the text in this document. 
						May be overridden at the sentence or word.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="dir" type="alphdt1:LanguageDirType" use="optional">
				<xs:annotation>
					<xs:documentation>
						Text direction for the text in this document. 
						May be overridden at the sentence or word.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="document_uri" type="xs:anyURI" use="required">
				<xs:annotation>
					<xs:documentation>Specifies a unique uri identifier for this treebank document</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="prefix" type="alphdt1:CitePrefixType">
				<xs:annotation>
					<xs:documentation>
						An optional list of prefix definitions for cite references and controlled vocabulary 
						terms used in attribute values in this document
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="sentenceType">
		<xs:annotation>
			<xs:documentation>Container for a sentence.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="alphdt1:LinkType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Use to specify links to provenance or format information for this sentence if it
						differs from that of the full document.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="comment" type="xs:anyType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						May be used to add sentence-level comments and metadata.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="word" type="treebank:wordType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="atok" type="treebank:tokenType" minOccurs="0" maxOccurs="unbounded"/> 
		</xs:sequence>
		<xs:attribute name="n" type="alphdt1:NSeqType" use="required">
			<xs:annotation>
				<xs:documentation>
					Sequential identifier for the sentence
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="cite" type="alphdt1:CiteType" use="optional">
			<xs:annotation>
				<xs:documentation>
					Cite reference for the sentence.		
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute ref="xml:lang" use="optional">
			<xs:annotation>
				<xs:documentation>
					Language code for the text in this sentence. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="alphdt1:LanguageDirType" use="optional">
			<xs:annotation>
				<xs:documentation>
					Text direction for the text in this sentence. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		
	</xs:complexType>

	<xs:complexType name="wordType" mixed="true">
		<xs:annotation>
			<xs:documentation>Container for a word token in a sentence. The token should actually appear in the sentence.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="alphdt1:LinkType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Use to specify links to provenance information for this word if it
						differs from that of the sentence or full document.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="comment" type="xs:anyType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						May be used to add word-level comments and metadata.
					</xs:documentation>
				</xs:annotation>
			</xs:element>	
		</xs:sequence>
		<xs:attribute name="n" type="treebank:WordIdType" use="required">
			<xs:annotation>
				<xs:documentation>
					Sequential identifier for the word
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="cite" type="alphdt1:CiteType" use="optional">
			<xs:annotation>
				<xs:documentation>
					Cite reference for the word
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="lemma" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					String representation of the lemma of this word 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="lemma_uri" type="xs:anyURI" use="optional">
			<xs:annotation>
				<xs:documentation>
					URI identifier for for the lemma of this word
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="form_uri" type="xs:anyURI" use="optional">
			<xs:annotation>
				<xs:documentation>
					URI identifier for for the morphological form of this word
					(Note if supplied, can eliminate the need for individual morphological
					attributes)
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="head" type="treebank:HeadType" use="optional">
			<xs:annotation>
				<xs:documentation>
					The @n value of the word on which this word depends.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute ref="xml:lang" use="optional">
			<xs:annotation>
				<xs:documentation>
					Language code for the text in this word. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="alphdt1:LanguageDirType" use="optional">
			<xs:annotation>
				<xs:documentation>
					Text direction for the text in this word. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="relation" type="treebank:RelationType" use="required">
			<xs:annotation>
				<xs:documentation>
					Relationship(s) between the word and its head. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:anyAttribute namespace="##any" processContents="lax"/>
	</xs:complexType>


	<xs:complexType name="tokenType" mixed="true">
		<xs:annotation>
			<xs:documentation>
				Generic container for a token that isn't physically present in the sentence but which can (or must) be supplied in order to produce
				a complete syntactic analysis of a sentence. This might, for example, be an ellided node, an implied to a word from another sentence,
			    a missing word in the extent physical representation of the sentence in the source material, etc.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="alphdt1:LinkType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Use to specify links to provenance information for this token if it
						differs from that of the sentence or full document.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="comment" type="xs:anyType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						May be used to add token-level comments and metadata.
					</xs:documentation>
				</xs:annotation>
			</xs:element>	
		</xs:sequence>
		<xs:attribute name="n" type="treebank:WordIdType" use="required">
			<xs:annotation>
				<xs:documentation>
					Sequential identifier for the token
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Semantic type of the token, preferably a URI reference to a controlled vocabulary term.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="lemma" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					String representation of the lemma of this token 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="lemma_uri" type="xs:anyURI" use="optional">
			<xs:annotation>
				<xs:documentation>
					URI identifier for for the lemma of this token
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="form_uri" type="xs:anyURI" use="optional">
			<xs:annotation>
				<xs:documentation>
					URI identifier for for the morphological form of this token
					(Note if supplied, can eliminate the need for individual morphological
					attributes)
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="insert_at" type="treebank:WordIdType" use="required">
			<xs:annotation>
				<xs:documentation>
					The insertion point (within the sentence) for the token in the form of the identifier of the
					word or token at which it should be inserted. The default is to insert the token before the 
					word or token identified here, but this should obey the insertion direction supplied in @insert_dir.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="insert_dir" default="before">
			<xs:annotation>
				<xs:documentation>
					The direction from the insertion point supplied in @insert_at that the token should be inserted 
					(i.e. before @insert_at or after @insert_at). Default if not supplied is 'before'.
				</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="after"/>
					<xs:enumeration value="before"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="head" type="treebank:HeadType" use="optional">
			<xs:annotation>
				<xs:documentation>
					The @n value of the word on which this token depends.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute ref="xml:lang" use="optional">
			<xs:annotation>
				<xs:documentation>
					Language code for the text in this word. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="alphdt1:LanguageDirType" use="optional">
			<xs:annotation>
				<xs:documentation>
					Text direction for the text in this word. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="relation" type="treebank:RelationType" use="required">
			<xs:annotation>
				<xs:documentation>
					Relationship(s) between the word and its head. 
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="display" type="xs:string" use="optional"></xs:attribute>
		<xs:anyAttribute namespace="##any" processContents="lax"/>
	</xs:complexType>
	

	<!-- Word identifier attribute -->
	<xs:simpleType name="WordIdType">
		<xs:annotation>
			<xs:documentation>
				Type of word id attribute: &lt;sentenceNumber&gt;-&lt;wordNumber&gt;
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9]+-[0-9]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HeadType">
		<xs:annotation>
			<xs:documentation>
				Head attribute type. 
				- value of -1 indicates the head is not yet set
				- value of 0 indicates the head is the root
				- positive non-zero value identifies the word id of the head word
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9]+-[0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="RelationType">
		<xs:annotation>
			<xs:documentation>Relation attribute type. 
				May be set to a space-separated list of URIs or SafeCURIE to allow for
				simple strings or controlled vocabulary terms specified via full uris or prefixes
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="alphdt1:URIorSafeCURIEsType"/>
	</xs:simpleType>
	
	
</xs:schema>

=== alpheios-project/schemas/examples/ellip1.xml
<treebank xmlns="http://data.perseus.org/ns/syntax/treebank/2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:alph="http://alpheios.net/rdfvocab/inflections/1"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:sgdt="http://data.perseus.org/rdfvocab/ns/syntax/smythgrammar/1"
    xsi:schemaLocation="http://data.perseus.org/ns/syntax/treebank/2 ../xsd/treebank-2.0.xsd"
    version="2.0" xml:lang="grc" dir="ltr"
    document_uri="http://data.perseus.org/collections/urn:cite:perseus:grctb.1.1"
    prefix="doc: urn:cts:latinLit:phi0448.phi001.perseus-lat1 
    aldt:http://data.perseus.org/rdfvocab/syntax/aldt#">

    <link xlink:role="http://www.w3.org/ns/prov#has_provenance" xlink:href="provenance-URI"/>
    <link xlink:role="http://www.w3.org/ns/prov#has_anchor" xlink:href="target-URI"/>
    <link xlink:role="http://purl.org/dc/terms/format"
        xlink:href="http://data.perseus.org/tagsets/syntax/aldt.json"/>
    <link xlink:role="http://purl.org/dc/terms/format"
        xlink:href="http://data.perseus.org/tagsets/syntax/sg.json"/>
    <comment class="title"> Sample treebank of Caesar De Bello Gallico to show use of use of new
        schema for ellipses </comment>

    <sentence n="1" cite="doc:2.1">
        <word n="1-1" lemma="conjuro" head="1-4" relation="aldt:ATR" alph:pofs="verb"
            alph:mood="participle" alph:num="singular" alph:case="genitive" alph:voice="active"
            alph:tense="present" alph:gend="neuter">Coniurandi</word>
        <word n="1-2" lemma="hic" head="1-4" relation="aldt:ATR" alph:pofs="adj" alph:num="plural"
            alph:case="accusative" alph:gend="feminine">has</word>
        <word n="1-3" lemma="sum" head="1-0" relation="aldt:ExD">esse</word>
        <word n="1-4" lemma="causa" head="1-3" relation="aldt:SBJ">causas</word>
        <word n="1-5" lemma="primus" head="1-6" relation="aldt:AuxY">primum</word>
        <word n="1-6" lemma="quod" head="1-3" relation="aldt:AuxC">quod</word>
        <word n="1-7" lemma="vereor" head="1-6" relation="aldt:PNOM">vererentur</word>
        <word n="1-8" lemma="ne" head="1-7" relation="aldt:AuxC">ne</word>
        <word n="1-9" lemma="comma" head="1-11" relation="aldt:AuxX">,</word>
        <word n="1-10" lemma="omnis" head="1-12" relation="aldt:ATR">omni</word>
        <word n="1-11" lemma="paco" head="1-18" relation="aldt:ADV">pacata</word>
        <word n="1-12" lemma="Gallia" head="1-11" relation="aldt:SBJ">Gallia</word>
        <word n="1-13" lemma="comma" head="1-11" relation="aldt:AuxX">,</word>
        <word n="1-14" lemma="ad" head="1-18" relation="aldt:AuxP">ad</word>
        <word n="1-15" lemma="is" head="1-14" relation="aldt:OBJ">eos</word>
        <word n="1-16" lemma="exercitus" head="1-18" relation="aldt:SBJ">exercitus</word>
        <word n="1-17" lemma="noster" head="1-16" relation="aldt:ATR">noster</word>
        <word n="1-18" lemma="adduco" head="1-8" relation="aldt:OBJ">adduceretur</word>
        <atok n="1-19" lemma="fio" head="1-0" insert_at="1-1" relation="aldt:PRED" display="fiebat" type="ellipsis"/>
        <atok n="1-20" lemma="certus" head="1-19" insert_at="1-19" insert_dir="after" relation="aldt:PNOM" display="certior" type="ellipsis"/>
    </sentence>
</treebank>

=== alpheios-project/schemas/examples/treebank.xml
<treebank xmlns="http://data.perseus.org/ns/syntax/treebank/2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:alph="http://alpheios.net/rdfvocab/inflections/1"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:sgdt="http://data.perseus.org/rdfvocab/ns/syntax/smythgrammar/1"
    xsi:schemaLocation="http://data.perseus.org/ns/syntax/treebank/2 ../xsd/treebank-2.0.xsd"
    version="2.0" 
    xml:lang="grc"
    dir="ltr"
    document_uri="http://data.perseus.org/collections/urn:cite:perseus:grctb.1.1"
    prefix="doc: urn:cts:greekLit:tlg0016.tlg001.perseus-grc1 
         aldt:http://data.perseus.org/rdfvocab/syntax/aldt#"
    >

    <link xlink:role="http://www.w3.org/ns/prov#has_provenance" xlink:href="provenance-URI"/>
    <link xlink:role="http://www.w3.org/ns/prov#has_anchor" xlink:href="target-URI"/>
    <link xlink:role="http://purl.org/dc/terms/format"
        xlink:href="http://data.perseus.org/tagsets/syntax/aldt.json"/>
    <link xlink:role="http://purl.org/dc/terms/format"
        xlink:href="http://data.perseus.org/tagsets/syntax/sg.json"/>
    <comment class="title"> Sample treebank of Herodotus Histories (from Vanessa Gorman's treebank)
        to show use of use of new schema </comment>
    <sentence n="1" cite="doc:1.1">
        <comment class="note"> Sample sentence level comment</comment>
        <word n="1-1" lemma="Ἡρόδοτος" head="1-3" relation="aldt:ATR" alph:pofs="noun"
            alph:num="singular" alph:gend="masculine" alph:case="genitive" sgdt:case="PRP"
            cite="doc:1.1@Ἡροδότου[1]">Ἡροδότου</word>
        <word n="1-2" lemma="Ἁλικαρνησσεύς" relation="aldt:ATR" alph:pofs="noun" alph:num="singular"
            alph:gend="masculine" alph:case="genitive" cite="doc:1.1@Ἁλικαρνησσέος[1]"
            >Ἁλικαρνησσέος</word>
        <word n="1-3" lemma="ἱστορία" head="1-4" relation="aldt:ATR" alph:pofs="noun"
            alph:num="singular" alph:gend="feminine" alph:case="genitive" cite="doc:1.1@ἱστορία[1]"
            >ἱστορία</word>
        <word n="1-4" lemma="ἀπόδειξις" head="1-0" relation="aldt:PNOM_ExD0_PRED" alph:pofs="noun"
            alph:num="singular" alph:gend="feminine" alph:case="nominative"
            cite="doc:1.1@ἀπόδεξις[1]">
            <comment class="note"> Sample word level comment</comment>
            ἀπόδεξις</word>
        <word n="1-5" lemma="ὅδε" head="1-0" relation="SBJ_ExD0_PRED" alph:pofs="pronoun"
            alph:num="singular" alph:gend="feminine" alph:case="nominative" cite="doc:1.1@ἥδε[1]"
            >ἥδε</word>

    </sentence>
</treebank>
